CREATE TABLE aaa (timeline TIMESTAMP);
CREATE EVENT e_test_insert
ON SCHEDULE EVERY 1 SECOND
DO INSERT INTO aaa VALUES(CURRENT_TIMESTAMP);


CREATE EVENT IFNOT EXISTS `Slave_Monitor`
ONSCHEDULE EVERY 5 SECOND
ONCOMPLETION PRESERVE
DO
CALL Slave_Monitor();



CREATE TABLE aaa (timeline TIMESTAMP);
CREATE EVENT e_test_insert
ON SCHEDULE EVERY 1 SECOND
DO INSERT INTO aaa VALUES(CURRENT_TIMESTAMP);
